file delete "e.o"
file delete "c.o"
file delete "a.out"

exec gcc -c -fPIC -o c.o $srcdir/$subdir/linking-clinkage.exporting.c
exec $objdir/engmac -I../  -c $srcdir/$subdir/linking-clinkage.em -o e.o
exec gcc c.o e.o $srcdir/$subdir/linking-clinkage.importing.c

spawn ./a.out 

expect {
    "FAIL"  {fail "Test failed.\n"}
    "DONE"  {pass "Test passed.\n"}
    default {fail "Test failed.\n"}
}

file delete "e.so"
file delete "c.o"
file delete "a.out"

exec gcc -c -fPIC -o c.o $srcdir/$subdir/linking-clinkage.exporting.c
exec $objdir/engmac --shared -I../  -c $srcdir/$subdir/linking-clinkage.em -o e.so
exec gcc c.o e.so $srcdir/$subdir/linking-clinkage.importing.c

spawn ./a.out 

expect {
    "FAIL"  {fail "Test failed.\n"}
    "DONE"  {pass "Test passed.\n"}
    default {fail "Test failed.\n"}
}